<?php

namespace App\Form;

use App\Entity\CompteGL1;
use App\Entity\ProduitCredit;
use App\Entity\PlanComptable;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompteGL1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ProduitCredit',EntityType::class,[
                'class'=>ProduitCredit::class,
                'choice_label'=>'NomProduitCredit',
                'by_reference'=>true,
                'mapped'=>true,
                'placeholder'=>'Choisir produit credit '
            ])
            ->add('CpteProvisionMauvaiseCreances',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CptePrincipaleEnCours',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CptePrvsionCoutMauvaiseCreance',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteInteretRecuCredit',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteCreditPassePerte',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteInteretEchus',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteInteretEchusRecevoir',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteRefinancementCredit',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CptePnlteComptabliliseAvance',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteRevenuePnlteComptblsAvnc',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteCommissionEchuesAccumulle',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteCommissionAccumulleGagne',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteRecvrmntCreanceDouteuse',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CptePapeterie',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteCheque',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteSurpaiement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteChargeCheque',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CpteCommissionCredit',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CptePnlteCrdt',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('DifferenceMonnaie',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('Papeterie',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('Commission',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('FraisDeveloppement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('FraisRefinancement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('PapeterieDecaissement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('CommisssionDecaissement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('MajorationDecaissement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('FraisDvlppmntDecaissement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
            ->add('FraisTraitementDecaissement',EntityType::class,[
                'class'=>PlanComptable::class,
                'choice_label'=>'Libelle',
                'by_reference'=>true,
                'mapped'=>true,
                'required'=>false,
                'placeholder'=>'Aucun'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CompteGL1::class,
        ]);
    }
}
